title: "José Francisco Pérez Vera"
description: "Portafolio profesional de un Ingeniero en Informática con experiencia en desarrollo y gestión de proyectos TI"
theme: jekyll-theme-minimal
show_downloads: false
google_analytics:
